@startuml
!define C4P https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master
!includeurl C4P/C4_Context.puml

title Identificación de Actores y Límites del Sistema\nGestión de Proyectos de Construcción
System_Boundary(c1, "Gestión de Proyectos de Construcción") {
    System(gestionCSC, "Gestión de Proyectos de Construcción", "Plataforma SaaS para la gestión, seguimiento y control de proyectos de construcción")
}

Person(cliente, "Cliente", "Dueño del proyecto de construcción")
Person(contratista, "Contratista", "Ejecuta y gestiona trabajos del proyecto")
Person(admin, "Administrador", "Gestiona usuarios, accesos y configuración del sistema")

System_Ext(keycloak, "Proveedor de autenticación y autorización", "IAM OAuth2 / OIDC")
System_Ext(storageProvider, "Servicio de Almacenamiento de archivos", "Almacenamiento en la nube")
System_Ext(notifProvider, "Servicio de Notificaciones", "SMS, Push, Email, WhatsApp")
System_Ext(paymentGateway, "Pasarela de Pagos", "Procesamiento de pagos")
System_Ext(transportProvider, "Proveedor de Transporte", "Transporte de materiales y equipos de construcción")
System_Ext(materialSupplier, "Proveedor de Materiales", "Suministro de materiales y equipos de construcción")

Rel(cliente, gestionCSC, "Consulta y da seguimiento a su proyecto de construcción")
Rel(contratista, gestionCSC, "Gestiona proyectos, recursos y procesos")
Rel(admin, gestionCSC, "Administra usuarios, accesos y configuración")

Rel(gestionCSC, keycloak, "Autenticación (OIDC)")
Rel(gestionCSC, storageProvider, "Carga archivos")
Rel(gestionCSC, notifProvider, "Envía notificaciones")
Rel(gestionCSC, paymentGateway, "Procesa pagos")
Rel(gestionCSC, transportProvider, "Solicita transporte")
Rel(gestionCSC, materialSupplier, "Pide materiales")


SHOW_LEGEND()
@enduml